import { CMaterialType } from '@chamn/model';

export const propMeta: CMaterialType['props'] = [
  {
    name: 'autoExpandParent',
    title: 'autoExpandParent',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'blockNode',
    title: 'blockNode',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'checkable',
    title: 'checkable',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'checkedKeys',
    title: 'checkedKeys',
    valueType: 'array',
    setters: ['ArraySetter', 'ExpressionSetter'],
  },
  {
    name: 'checkStrictly',
    title: 'checkStrictly',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'defaultCheckedKeys',
    title: 'defaultCheckedKeys',
    valueType: 'array',
    setters: ['ArraySetter'],
  },
  {
    name: 'defaultExpandAll',
    title: 'defaultExpandAll',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'defaultExpandedKeys',
    title: 'defaultExpandedKeys',
    valueType: 'array',
    setters: ['ArraySetter'],
  },
  {
    name: 'defaultExpandParent',
    title: 'defaultExpandParent',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'defaultSelectedKeys',
    title: 'defaultSelectedKeys',
    valueType: 'array',
    setters: ['ArraySetter'],
  },
  {
    name: 'disabled',
    title: 'disabled',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'draggable',
    title: 'draggable',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'expandedKeys',
    title: 'expandedKeys',
    valueType: 'array',
    setters: ['ArraySetter', 'ExpressionSetter'],
  },
  {
    name: 'filterTreeNode',
    title: 'filterTreeNode',
    valueType: 'object',
    setters: ['ExpressionSetter', 'FunctionSetter'],
  },
  {
    name: 'loadData',
    title: 'loadData',
    valueType: 'object',
    setters: ['ExpressionSetter', 'FunctionSetter'],
  },
  {
    name: 'loadedKeys',
    title: 'loadedKeys',
    valueType: 'array',
    setters: ['ArraySetter', 'ExpressionSetter'],
  },
  {
    name: 'multiple',
    title: 'multiple',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'selectable',
    title: 'selectable',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'selectedKeys',
    title: 'selectedKeys',
    valueType: 'array',
    setters: ['ArraySetter', 'ExpressionSetter'],
  },
  {
    name: 'showIcon',
    title: 'showIcon',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'showLine',
    title: 'showLine',
    valueType: 'boolean',
    setters: ['BooleanSetter', 'JSONSetter'],
  },
  {
    name: 'treeData',
    title: 'treeData',
    valueType: 'array',
    setters: ['ArraySetter', 'JSONSetter', 'ExpressionSetter'],
  },
  {
    name: 'virtual',
    title: 'virtual',
    valueType: 'boolean',
    setters: ['BooleanSetter'],
  },
  {
    name: 'style',
    title: 'style',
    valueType: 'object',
    setters: ['JSONSetter'],
  },
  {
    name: 'className',
    title: 'className',
    valueType: 'string',
    setters: ['StringSetter'],
  },
];
